/* Physics Solved — build.
 * Concatenates the source CSS + JS in a fixed order and writes the two dist
 * bundles. If esbuild is installed it is used to minify; otherwise a safe
 * concat (with light CSS whitespace stripping) is written instead — so the
 * build always works with zero required dependencies.
 *
 *   node scripts/build.mjs
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Order matters: tokens define the vars components use; core defines PS before
// components register on it.
const CSS_FILES = [
  "src/css/tokens.css",
  "src/css/components.css",
  "src/css/print.css"
];
const JS_FILES = [
  "src/js/core.js",
  "src/js/grading-adapter.js",
  "src/js/components/carousel.js",
  "src/js/components/equation-finder.js",
  "src/js/components/formula-library.js",
  "src/js/components/frq.js",
  "src/js/components/simulator-kinematics.js",
  "src/js/components/portfolio.js"
];

const BANNER = "/* Physics Solved bundle — generated by scripts/build.mjs. Edit src/, not dist/. */\n";

async function concat(files) {
  const parts = [];
  for (const f of files) {
    parts.push("/* --- " + f + " --- */");
    parts.push(await readFile(path.join(ROOT, f), "utf8"));
  }
  return parts.join("\n");
}

// Conservative CSS minifier: strips comments and needless whitespace WITHOUT
// touching whitespace around ":" (would break descendant selectors like
// ".ps-root :focus-visible").
function lightCssMinify(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{};,])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

async function loadEsbuild() {
  try {
    return await import("esbuild");
  } catch {
    return null;
  }
}

function kb(str) {
  return (Buffer.byteLength(str, "utf8") / 1024).toFixed(1) + " KB";
}

async function run() {
  await mkdir(path.join(ROOT, "dist"), { recursive: true });
  const esbuild = await loadEsbuild();

  const cssSrc = await concat(CSS_FILES);
  const jsSrc = await concat(JS_FILES);

  let cssOut, jsOut, mode;
  if (esbuild) {
    mode = "esbuild (minified)";
    cssOut = (await esbuild.transform(cssSrc, { loader: "css", minify: true })).code;
    jsOut = (await esbuild.transform(jsSrc, { loader: "js", minify: true, target: "es2020" })).code;
  } else {
    mode = "concat (esbuild not found — install it for true minification)";
    cssOut = lightCssMinify(cssSrc);
    jsOut = jsSrc;
  }

  const cssPath = path.join(ROOT, "dist", "physics-solved.min.css");
  const jsPath = path.join(ROOT, "dist", "physics-solved.min.js");
  await writeFile(cssPath, BANNER + cssOut + "\n");
  await writeFile(jsPath, BANNER + jsOut + "\n");

  console.log("Physics Solved build — " + mode);
  console.log("  dist/physics-solved.min.css  " + kb(cssOut));
  console.log("  dist/physics-solved.min.js   " + kb(jsOut));
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
